sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: REDACTED_OSS_KEY
    access-key-secret: REDACTED_OSS_SECRET
    bucket-name: java-waimai2
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  shop:
    address: 北京市海淀区中关村大街1号
  baidu:
    ak: 你的百度地图AK
  wechat:
    appid: REDACTED_WECHAT_APPID
    secret: REDACTED_WECHAT_SECRET
    mchid: 1
    mchSerialNo: 1
    privateKeyFilePath: /
    apiV3Key: 1
    weChatPayCertFilePath: /
    notifyUrl: http://localhost
    refundNotifyUrl: http://localhost