sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ${DB_PASSWORD:}
  alioss:
    endpoint: ${OSS_ENDPOINT:}
    access-key-id: ${OSS_ACCESS_KEY_ID:}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
    bucket-name: ${OSS_BUCKET_NAME:}
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    database: 0
  shop:
    address: 北京市海淀区中关村大街1号
  baidu:
    ak: ${BAIDU_AK:}
  wechat:
    appid: ${WECHAT_APPID:}
    secret: ${WECHAT_SECRET:}
    mchid: ${WECHAT_MCHID:}
    mchSerialNo: ${WECHAT_MCH_SERIAL_NO:}
    privateKeyFilePath: ${WECHAT_PRIVATE_KEY_PATH:}
    apiV3Key: ${WECHAT_API_V3_KEY:}
    weChatPayCertFilePath: ${WECHAT_PAY_CERT_PATH:}
    notifyUrl: ${WECHAT_NOTIFY_URL:}
    refundNotifyUrl: ${WECHAT_REFUND_NOTIFY_URL:}